name: Terraform workflow

on: workflow_dispatch

jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWSRalf}}
          aws-secret-access-key: ${{secrets.awsRalf1}}
          aws-region: eu-central-1

      - name: Terraform Init
        
        run: terraform init

      - name: Terraform Apply
        
        run: terraform apply -auto-approve
